---
- name: main playbook
  hosts: all
  become: True
  gather_facts: True
  tasks:
    - name: Update all packages
      yum:
          name: '*'
          state: latest
          update_only: yes
    - name: install packages
      yum:
         name:
           - git
           - python-pip
           - yum-utils
         state: present


    - name: add docker-ce-repo
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/ubuntu/gpg
      

    - name: install docker stuff
      package:
         name: 
           - docker
         state: present

    
    - name: start and enable
      service:
         name: docker
         state: started
         enabled: yes
    - name: copy ssh key
      become: no
      become_user: ec2-user
      copy:
         src: ~/.ssh/keypair.pem
         dest: ~/.ssh/keypair.pem

    - name: Clone a private Git repository
      become: no
      become_user: ec2-user
      git:
        repo: https://github.com/guytamari/ci-cd-workshop.git
        dest: /home/ec2-user/github-repo
        accept_hostkey: yes
        key_file: /home/ec2-user/.ssh/id_rsa.pub
      register: git_status


    - name: login to dockerhub
      #when: git_status.changed == true
      docker_login:
        config_path: /home/ec2-user/.docker/config.json
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: Build and push to dockerhub
      #when: git_status.changed == true
      docker_image:
        build:
          path: "/home/ec2-user/github-repo/src"
        name: guytamari/js-app
        tag: "{{ item }}"
        push: yes
        source: build
      with_items:
        - "latest"
        - "{{ git_status.after }}"
    - name: run container
      shell: |
        docker run -d  guytamari/js-app:"{{git_status.after}}"
    
    
    - name: Run `docker compose up` again
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user/github-repo/src
