pipeline {
    agent any
    environment {
        SSH_FILE  = credentials('ec2-user')
    }

    stages {
        stage('build and deploy') {
            steps {
                ansiblePlaybook(
                    playbook: 'ansible-playbook/create-configure-infa.yaml',
                    inventory: 'ansible-playbook/inventory.yaml',
                    credentialsId: "ec2-user",
                    hostKeyChecking: 'False'
                    )
            }
        }
    }
}
