pipeline {
    agent any

    stages {
        stage('build and deploy') {
            steps {
                ansiblePlaybook inventory: 'inventory.yaml' playbook: 'create-configure-infa.yaml'
            }
        }
    }
}
