pipeline {
    agent any
    stages {
        stage('debug') {
            steps { 
                sh'''
                    echo $SSH_FILE
                    echo $ec2-user
                '''
            }
        }
        stage('build and deploy') {
            steps {
                withEnv(["ANSIBLE_HOST_KEY_CHECKING=False"]) { // Disable SSH host key checking
                    ansiblePlaybook(
                        playbook: 'ansible-playbook/create-configure-infa.yaml',
                        inventory: 'ansible-playbook/inventory.yaml',
                        credentialsId: 'ec2-private-key',
                        hostKeyChecking: 'false',
                        extraVars: [
                            ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/id_ed25519"
                        ]
                    )
                }
            }
        }
    }
}
